name: Run JMeter Test and Publish HTML

on:
  push:
    branches:
      - main
  schedule:
    - cron: "30 16 * * *"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  jmeter-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout repo
        uses: actions/checkout@v3

        # 2. Setup Java
      - name: Setup Java 11
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "11"

        # 3. Install JMeter
      - name: Install Apache JMeter
        run: |
          wget https://downloads.apache.org/jmeter/binaries/apache-jmeter-5.6.3.tgz
          tar -xzf apache-jmeter-5.6.3.tgz
          mv apache-jmeter-5.6.3 jmeter

        # 4. Create reports folder
      - name: Create reports folder
        run: mkdir -p reports

        # 5. Run JMeter test
      - name: Run JMeter test
        run: |
          jmeter/bin/jmeter -n -t load-test.jmx -l reports/result.jtl

        # 6. **Set Timezone ke WIB sebelum generate report**
      - name: Set Timezone to WIB
        run: sudo timedatectl set-timezone Asia/Jakarta

        # 7. Generate JMeter HTML report
      - name: Generate JMeter HTML report
        run: |
          jmeter/bin/jmeter -g reports/result.jtl -o reports/html -Juser.timezone=Asia/Jakarta

        # 8. Deploy ke GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./reports/html
